### ISSUE TITLE
Docker Registry config and usage

### ISSUE THREAD

**Issue by arnabsinha4u** [ing-bank/ansible-selenium-grid#2]
When a custom docker registry is configured, the docker role does not have defaults/main.yml where it can be done. It has to be passed on from the CLI.
Thus, this also overrides the docker.io default in the roles of selenium.
Further more, there is inconsistency in the way an image is pulled and the images are started up. They could all be appended with either a registry name or use no registry name at all.

My proposal would be the following:
1) Include a defaults/main.yml in docker role or use an assertion, though i do not prefer an assertion in this case
2) Remove the registry name from the image pull as Docker Engine and rely on its intelligence to route to the configured registry. It works. This will also bulletproof the solution in case there are any local images which have been retagged. Generally enterprises will not use a direct pull but post hardening.

**Comment by rjongejan** [comment]
As this is solved by PR 3, this issue can be closed. Thanks for submitting, and solving, the issue.
